stages:
    - test
    - build
    - deploy
    
pages:
    stage: deploy
    script:
        - mkdir .public
        - sbcl --load generate-docs.lisp --disable-debuger --quit
        - cp -r ./doc/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master



image : daewok/lisp-devel

before_script:
        - ln -s "${CI_PROJECT_DIR}" ~/quicklisp/local-projects/cl-matrix

test:
    stage: test
    script:
        - sbcl --load ci-tests.lisp --disable-debugger --quit
