stages:
    - test
    - build
    - deploy
    
pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r ./doc/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master



image : daewok/lisp-devel

before_script:
        - ln -s "${CI_PROJECT_DIR}" ~/quicklisp/local-projects/cl-matrix
	- git clone https://gitlab.com/Gnuxie/method-hooks.git ~/quicklisp/local-projects/method-hooks

test:
    stage: test
    script:
        - sbcl --load ci-tests.lisp --disable-debugger --quit
