(defpackage :CL-MATRIX.API.CLIENT (:use #:cl #:cl-matrix.autowrap.runtime #:cl-matrix.autowrap.authentication)
  (:import-from :CL-MATRIX.AUTOWRAP.AUTHENTICATION
  #:AUTH
  #:ACCESS-TOKEN
  #:HOMESERVER
  #:QUERY-PARAM)
  (:export
  #:delete-devices
  #:put-directory/list/room/roomid
  #:get-profile/userid
  #:get-rooms/roomid/state/eventtype/statekey
  #:get-account/whoami
  #:put-rooms/roomid/redact/eventid/txnid
  #:get-events
  #:get-presence/list/userid
  #:get-thirdparty/user
  #:post-account/password/email/requesttoken
  #:put-user/userid/rooms/roomid/account-data/type
  #:post-register/msisdn/requesttoken
  #:post-rooms/roomid/ban
  #:get-rooms/roomid/event/eventid
  #:post-rooms/roomid/join
  #:post-search
  #:post-rooms/roomid/read-markers
  #:post-delete-devices
  #:delete-devices/deviceid
  #:get-rooms/roomid/members
  #:get-directory/room/roomalias
  #:get-thirdparty/location/protocol
  #:get-thirdparty/protocols
  #:get-pushrules/scope/kind/ruleid/actions
  #:put-directory/room/roomalias
  #:get-thirdparty/protocol/protocol
  #:post-register/email/requesttoken
  #:get-rooms/roomid/state
  #:get-notifications
  #:get-rooms/roomid/state/eventtype
  #:put-profile/userid/avatar-url
  #:get-rooms/roomid/context/eventid
  #:post-account/3pid/email/requesttoken
  #:get-login/cas/redirect
  #:post-createroom
  #:get-pushers
  #:post-account/deactivate
  #:get-rooms/roomid/initialsync
  #:get-user/userid/rooms/roomid/tags
  #:get-pushrules/
  #:put-rooms/roomid/state/eventtype
  #:get-joined-rooms
  #:post-logout
  #:put-presence/userid/status
  #:post-account/password/msisdn/requesttoken
  #:put-pushrules/scope/kind/ruleid/actions
  #:post-account/3pid/delete
  #:get-devices/deviceid
  #:get-user/userid/filter/filterid
  #:post-register
  #:get-keys/changes
  #:post-rooms/roomid/kick
  #:get-sync
  #:post-rooms/roomid/invite
  #:post-logout/all
  #:post-account/3pid
  #:get-login/cas/ticket
  #:post-publicrooms
  #:put-user/userid/account-data/type
  #:get-directory/list/room/roomid
  #:get-rooms/roomid/messages
  #:put-devices/deviceid
  #:get-thirdparty/location
  #:post-login
  #:get-pushrules/scope/kind/ruleid/enabled
  #:post-account/password
  #:delete-pushrules/scope/kind/ruleid
  #:delete-directory/room/roomalias
  #:post-rooms/roomid/receipt/receipttype/eventid
  #:get-admin/whois/userid
  #:get-account/3pid
  #:post-user/userid/filter
  #:get-events/eventid
  #:post-user-directory/search
  #:put-pushrules/scope/kind/ruleid
  #:get-publicrooms
  #:put-pushrules/scope/kind/ruleid/enabled
  #:post-join/roomidoralias
  #:put-sendtodevice/eventtype/txnid
  #:post-rooms/roomid/forget
  #:post-rooms/roomid/leave
  #:put-rooms/roomid/state/eventtype/statekey
  #:get-initialsync
  #:get-presence/userid/status
  #:get-register/available
  #:get-login
  #:get-pushrules/scope/kind/ruleid
  #:get-rooms/roomid/joined-members
  #:delete-user/userid/rooms/roomid/tags/tag
  #:get-devices
  #:post-keys/upload
  #:get-voip/turnserver
  #:post-keys/claim
  #:post-presence/list/userid
  #:put-profile/userid/displayname
  #:put-rooms/roomid/send/eventtype/txnid
  #:post-pushers/set
  #:put-user/userid/rooms/roomid/tags/tag
  #:get-thirdparty/user/protocol
  #:post-account/3pid/msisdn/requesttoken
  #:put-rooms/roomid/typing/userid
  #:get-profile/userid/displayname
  #:post-keys/query
  #:get-profile/userid/avatar-url
  #:post-user/userid/openid/request-token
  #:post-rooms/roomid/unban
  #:post-rooms/roomid/report/eventid))
(in-package :CL-MATRIX.API.CLIENT)
