
("GET /_matrix/client/versions" "GET /.well-known/matrix/client"
 "GET /_matrix/client/r0/login" "POST /_matrix/client/r0/login"
 "POST /_matrix/client/r0/logout" "POST /_matrix/client/r0/logout/all"
 "POST /_matrix/client/r0/register"
 "POST /_matrix/client/r0/register/email/requestToken"
 "POST /_matrix/client/r0/register/msisdn/requestToken"
 "POST /_matrix/client/r0/account/password"
 "POST /_matrix/client/r0/account/password/email/requestToken"
 "POST /_matrix/client/r0/account/password/msisdn/requestToken"
 "POST /_matrix/client/r0/account/deactivate"
 "GET /_matrix/client/r0/register/available"
 "GET /_matrix/client/r0/account/3pid" "POST /_matrix/client/r0/account/3pid"
 "POST /_matrix/client/r0/account/3pid/delete"
 "POST /_matrix/client/r0/account/3pid/email/requestToken"
 "POST /_matrix/client/r0/account/3pid/msisdn/requestToken"
 "GET /_matrix/client/r0/account/whoami"
 "POST /_matrix/client/r0/user/{userId}/filter"
 "GET /_matrix/client/r0/user/{userId}/filter/{filterId}"
 "GET /_matrix/client/r0/sync" "GET /_matrix/client/r0/events"
 "GET /_matrix/client/r0/initialSync" "GET /_matrix/client/r0/events/{eventId}"
 "GET /_matrix/client/r0/rooms/{roomId}/event/{eventId}"
 "GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}"
 "GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}"
 "GET /_matrix/client/r0/rooms/{roomId}/state"
 "GET /_matrix/client/r0/rooms/{roomId}/members"
 "GET /_matrix/client/r0/rooms/{roomId}/joined_members"
 "GET /_matrix/client/r0/rooms/{roomId}/messages"
 "GET /_matrix/client/r0/rooms/{roomId}/initialSync"
 "PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}"
 "PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}"
 "PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}"
 "m.room.redaction"
 "PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}"
 "POST /_matrix/client/r0/createRoom"
 "PUT /_matrix/client/r0/directory/room/{roomAlias}"
 "GET /_matrix/client/r0/directory/room/{roomAlias}"
 "DELETE /_matrix/client/r0/directory/room/{roomAlias}"
 "GET /_matrix/client/r0/joined_rooms"
 "POST /_matrix/client/r0/rooms/{roomId}/invite"
 "POST /_matrix/client/r0/rooms/{roomId}/join"
 "POST /_matrix/client/r0/join/{roomIdOrAlias}"
 "POST /_matrix/client/r0/rooms/{roomId}/leave"
 "POST /_matrix/client/r0/rooms/{roomId}/forget"
 "POST /_matrix/client/r0/rooms/{roomId}/kick"
 "POST /_matrix/client/r0/rooms/{roomId}/ban"
 "POST /_matrix/client/r0/rooms/{roomId}/unban"
 "GET /_matrix/client/r0/directory/list/room/{roomId}"
 "PUT /_matrix/client/r0/directory/list/room/{roomId}"
 "GET /_matrix/client/r0/publicRooms" "POST /_matrix/client/r0/publicRooms"
 "POST /_matrix/client/r0/user_directory/search"
 "PUT /_matrix/client/r0/profile/{userId}/displayname"
 "GET /_matrix/client/r0/profile/{userId}/displayname"
 "PUT /_matrix/client/r0/profile/{userId}/avatar_url"
 "GET /_matrix/client/r0/profile/{userId}/avatar_url"
 "GET /_matrix/client/r0/profile/{userId}" "m.room.aliases"
 "m.room.canonical_alias" "m.room.create" "m.room.join_rules" "m.room.member"
 "m.room.power_levels" "m.room.redaction" "Web" "Mobile" "Desktop" "CLI"
 "Embedded" "m.room.message" "m.room.message.feedback" "m.room.name"
 "m.room.topic" "m.room.avatar" "m.room.pinned_events" "m.text" "m.emote"
 "m.notice" "m.image" "m.file" "m.video" "m.audio" "m.location" "m.text"
 "m.notice" "m.emote" "m.image" "m.video" "m.audio" "m.file" "m.call.invite"
 "m.call.candidates" "m.call.answer" "m.call.hangup"
 "GET /_matrix/client/r0/voip/turnServer" "m.typing"
 "PUT /_matrix/client/r0/rooms/{roomId}/typing/{userId}" "m.receipt"
 "POST /_matrix/client/r0/rooms/{roomId}/receipt/{receiptType}/{eventId}"
 "m.fully_read" "POST /_matrix/client/r0/rooms/{roomId}/read_markers"
 "m.presence" "PUT /_matrix/client/r0/presence/{userId}/status"
 "GET /_matrix/client/r0/presence/{userId}/status"
 "POST /_matrix/client/r0/presence/list/{userId}"
 "GET /_matrix/client/r0/presence/list/{userId}"
 "POST /_matrix/media/r0/upload"
 "GET /_matrix/media/r0/download/{serverName}/{mediaId}"
 "GET /_matrix/media/r0/download/{serverName}/{mediaId}/{fileName}"
 "GET /_matrix/media/r0/thumbnail/{serverName}/{mediaId}"
 "GET /_matrix/media/r0/preview_url" "GET /_matrix/media/r0/config"
 "PUT /_matrix/client/r0/sendToDevice/{eventType}/{txnId}"
 "GET /_matrix/client/r0/devices" "GET /_matrix/client/r0/devices/{deviceId}"
 "PUT /_matrix/client/r0/devices/{deviceId}"
 "DELETE /_matrix/client/r0/devices/{deviceId}"
 "POST /_matrix/client/r0/delete_devices" "m.message"
 "m.olm.v1.curve25519-aes-sha2" "m.megolm.v1.aes-sha2" "m.room.encryption"
 "m.room.encrypted" "m.room_key" "m.room_key_request" "m.forwarded_room_key"
 "POST /_matrix/client/r0/keys/upload" "POST /_matrix/client/r0/keys/query"
 "POST /_matrix/client/r0/keys/claim" "GET /_matrix/client/r0/keys/changes"
 "m.room.history_visibility" "GET /_matrix/client/r0/pushers"
 "POST /_matrix/client/r0/pushers/set" "GET /_matrix/client/r0/notifications"
 ".m.rule.master" ".m.rule.suppress_notices" ".m.rule.invite_for_me"
 ".m.rule.member_event" ".m.rule.contains_display_name" ".m.rule.roomnotif"
 ".m.rule.contains_user_name" ".m.rule.call"
 ".m.rule.encrypted_room_one_to_one" ".m.rule.room_one_to_one"
 ".m.rule.message" ".m.rule.encrypted" "GET /_matrix/client/r0/pushrules/"
 "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}"
 "DELETE /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}"
 "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled"
 "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions"
 "m.room.third_party_invite" "POST /_matrix/client/r0/rooms/{roomId}/invite"
 "POST /_matrix/client/r0/search" "room_events" "m.room.guest_access"
 "GET /_matrix/client/r0/events" "m.tag"
 "GET /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags"
 "PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}"
 "DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}"
 "PUT /_matrix/client/r0/user/{userId}/account_data/{type}"
 "PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/account_data/{type}"
 "GET /_matrix/client/r0/admin/whois/{userId}"
 "GET /_matrix/client/r0/rooms/{roomId}/context/{eventId}"
 "GET /_matrix/client/r0/login/cas/redirect"
 "GET /_matrix/client/r0/login/cas/ticket" "m.direct" "m.ignored_user_list"
 "m.sticker" "POST /_matrix/client/r0/rooms/{roomId}/report/{eventId}"
 "GET /_matrix/client/r0/thirdparty/protocols"
 "GET /_matrix/client/r0/thirdparty/protocol/{protocol}"
 "GET /_matrix/client/r0/thirdparty/location/{protocol}"
 "GET /_matrix/client/r0/thirdparty/user/{protocol}"
 "GET /_matrix/client/r0/thirdparty/location"
 "GET /_matrix/client/r0/thirdparty/user"
 "POST /_matrix/client/r0/user/{userId}/openid/request_token"
 "m.room.server_acl" "POST /user_directory/search"
 "GET /rooms/{roomId}/event/{eventId}" "POST /delete_devices"
 "GET /thirdparty/*" "POST /account/3pid/msisdn/requestToken"
 "POST /register/msisdn/requestToken"
 "POST /account/password/msisdn/requestToken" "POST /account/3pid/delete"
 "POST /rooms/{roomId}/read_markers" "set_presence" "/sync" "token"
 "/keys/query" "/register/available" "@room" "/logout/all" "allow_remote"
 "m.room.encrypted" "m.room.encryption" "m.room_key"
 "device_one_time_keys_count" "device_lists:left" ".well-known" "/login"
 "server_name" "/join/{roomIdOrAlias}" "m.text" "m.emote" "@room"
 "validated_at" "added_at" "GET /acount/3pid" "inhibit_login" "home_server"
 "/login" "/register" "/keys/changes" "/search" "m.presence" "m.tag"
 "/account/whoami" "ImageInfo" "ThumbnailInfo" "GET /rooms/{roomId}/members"
 "changed" "StateEvent" "/createRoom" "reason" "GET /presence/{userId}/status"
 "/createRoom" "RoomEvent" "/rooms/{roomId}/messages" "/search" "/createRoom"
 "invite_room_state" "unsigned" "type: number" "/sync" "/sync"
 "PUT /directory/room" "/requestToken" "errcode" "application/json"
 "access_token" "/delete_devices" "/createRoom" "error" "errcode" "M_FORBIDDEN"
 "com.mydomain.here" "FORBIDDEN" "COM.MYDOMAIN.HERE_FORBIDDEN" "error"
 "errcode" "M_UNKNOWN" "M_NOT_FOUND" "M_UNKNOWN" "M_FORBIDDEN"
 "M_UNKNOWN_TOKEN" "M_MISSING_TOKEN" "M_BAD_JSON" "M_NOT_JSON" "M_NOT_FOUND"
 "M_LIMIT_EXCEEDED" "M_UNKNOWN" "M_UNRECOGNIZED" "M_UNAUTHORIZED"
 "M_USER_IN_USE" "M_INVALID_USERNAME" "M_ROOM_IN_USE" "createRoom"
 "M_INVALID_ROOM_STATE" "createRoom" "M_THREEPID_IN_USE" "M_THREEPID_NOT_FOUND"
 "M_THREEPID_AUTH_FAILED" "M_THREEPID_DENIED" "M_SERVER_NOT_TRUSTED"
 "M_UNSUPPORTED_ROOM_VERSION" "M_INCOMPATIBLE_ROOM_VERSION" "room_version"
 "M_BAD_STATE" "M_GUEST_ACCESS_FORBIDDEN" "M_CAPTCHA_NEEDED"
 "M_CAPTCHA_INVALID" "M_MISSING_PARAM" "M_INVALID_PARAM" "M_TOO_LARGE"
 "M_EXCLUSIVE" "HTTP PUT" "{txnId}" "POST" "PUT" "GET /_matrix/client/versions"
 "rX.Y.Z" "Z" "X.Y" "r0.0.0" "r0.0.1" "r1.2.0" "r0.0.1" "r1.2.0" "OPTIONS"
 "PROMPT" "IGNORE" "FAIL_PROMPT" "PROMPT" "FAIL_ERROR" ".well-known"
 "https://hostname/.well-known/matrix/client" "IGNORE" "FAIL_PROMPT"
 "FAIL_PROMPT" "base_url" "m.homeserver" "FAIL_PROMPT" "FAIL_ERROR"
 "/_matrix/client/versions" "FAIL_ERROR" "m.identity_server" "base_url"
 "/_matrix/identity/api/v1" "m.identity_server" "base_url" "FAIL_ERROR"
 "GET /.well-known/matrix/client" "com.example.myapp.property" "access_token"
 "Bearer $access_token" "access_token=TheTokenHere"
 "Authorization: Bearer TheTokenHere" "Authorization" "Authorization"
 "M_MISSING_TOKEN" "M_UNKNOWN_TOKEN" "device_id" "device_id" "device_id"
 "device_id" "auth" "auth" "flows" "auth" "type" "session" "example.type.foo"
 "completed" "errcode" "error" "m.login.dummy" "m.login.password"
 "m.login.recaptcha" "m.login.oauth2" "m.login.email.identity" "m.login.token"
 "m.login.dummy" "m.login.password" "identifier" "/account/3pid" "user"
 "m.login.recaptcha" "m.login.token" "nonce" "nonce" "token" "txn_id" "txn_id"
 "token" "m.login.oauth2" "uri" "redirect URI" "service selection URI"
 "Authorization Request URI" "Authorization Request URI"
 "Authorization Request URI" "redirect URI" "redirect URI"
 "m.login.email.identity" "m.login.dummy" "auth type" "session ID" "onAuthDone"
 "type" "m.id.user" "m.id.thirdparty" "m.id.phone" "m.id.user"
 "m.id.thirdparty" "/account/3pid" "m.id.phone" "/account/3pid"
 "m.id.thirdparty" "medium" "msisdn" "/login" "/login" "/account/3pid" "user"
 "403 Forbidden" "/login" "token" "403 Forbidden" "M_FORBIDDEN"
 "GET /_matrix/client/r0/login" "type" "type" "POST /_matrix/client/r0/login"
 "device_id" "device_id" "identifier" "identifier" "identifier" "type"
 "m.login.password" "type" "m.login.token" "device_id" "user_id" "homeserver"
 "POST /_matrix/client/r0/logout" "POST /_matrix/client/r0/logout/all"
 "window.onLogin" "POST /_matrix/client/r0/register" "device_id" "username"
 "username" "user_id" "username" "M_INVALID_USERNAME" "user_id" "username"
 "device_id" "register" "device_id" "access_token" "device_id" "inhibit_login"
 "user_id" "homeserver" "inhibit_login" "M_USER_IN_USE" "M_INVALID_USERNAME"
 "M_EXCLUSIVE" "POST /_matrix/client/r0/register/email/requestToken"
 "validate/email/requestToken" "[0-9a-zA-Z.=_-]" "send_attempt" "email"
 "client_secret" "[0-9a-zA-Z.=_-]" "M_THREEPID_IN_USE" "M_SERVER_NOT_TRUSTED"
 "id_server" "POST /_matrix/client/r0/register/msisdn/requestToken"
 "validate/msisdn/requestToken" "[0-9a-zA-Z.=_-]" "phone_number" "send_attempt"
 "country" "phone_number" "client_secret" "[0-9a-zA-Z.=_-]" "M_THREEPID_IN_USE"
 "M_SERVER_NOT_TRUSTED" "id_server" "POST /_matrix/client/r0/account/password"
 "POST /_matrix/client/r0/account/password/email/requestToken"
 "validate/email/requestToken" "/register/email/requestToken" "[0-9a-zA-Z.=_-]"
 "send_attempt" "email" "client_secret" "[0-9a-zA-Z.=_-]"
 "POST /_matrix/client/r0/account/password/msisdn/requestToken"
 "validate/msisdn/requestToken" "/register/msisdn/requestToken"
 "[0-9a-zA-Z.=_-]" "phone_number" "send_attempt" "country" "phone_number"
 "client_secret" "[0-9a-zA-Z.=_-]" "POST /_matrix/client/r0/account/deactivate"
 "GET /_matrix/client/r0/register/available" "true" "M_USER_IN_USE"
 "M_INVALID_USERNAME" "M_EXCLUSIVE" "M_WEAK_PASSWORD"
 "GET /_matrix/client/r0/account/3pid" "POST /_matrix/client/r0/account/3pid"
 "false" "POST /_matrix/client/r0/account/3pid/delete"
 "POST /_matrix/client/r0/account/3pid/email/requestToken"
 "validate/email/requestToken" "/register/email/requestToken" "[0-9a-zA-Z.=_-]"
 "send_attempt" "email" "client_secret" "[0-9a-zA-Z.=_-]"
 "POST /_matrix/client/r0/account/3pid/msisdn/requestToken"
 "validate/msisdn/requestToken" "/register/msisdn/requestToken"
 "[0-9a-zA-Z.=_-]" "phone_number" "send_attempt" "country" "phone_number"
 "client_secret" "[0-9a-zA-Z.=_-]" "GET /_matrix/client/r0/account/whoami"
 "user_id" "user_id" "from" "to" "limit" "dir" "from" "to" "[a-zA-Z0-9.=_-]+"
 "dir" "f" "b" "chunk" "prev_batch"
 "POST /_matrix/client/r0/user/{userId}/filter" "'senders'" "'types'" "'*'"
 "'rooms'" "ephemeral" "state" "timeline" "account_data" "ephemeral" "state"
 "timeline" "account_data" "'senders'" "'types'" "'*'" "'rooms'" "true" "url"
 "false" "false" "{" "GET /_matrix/client/r0/user/{userId}/filter/{filterId}"
 "'senders'" "'types'" "'*'" "'rooms'" "ephemeral" "state" "timeline"
 "account_data" "ephemeral" "state" "timeline" "account_data" "'senders'"
 "'types'" "'*'" "'rooms'" "true" "url" "false" "false" "type" "state_key" "m."
 "type" "com.example.myapp.event" "/sync" "since" "next_batch" "since" "/sync"
 "prev_batch" "start" "/rooms/<room_id>/messages" "/sync" "next_batch" "since"
 "timeout" "/sync" "/events" "/sync" "/sync" "/rooms/<room_id>/messages"
 "/sync" "state" "timeline" "state" "since" "state" "timeline" "state" "state"
 "since" "timeline" "limited" "state" "timeline" "state" "state" "timeline"
 "state" "GET /_matrix/client/r0/sync" "\"{\"" "true" "since" "since" "timeout"
 "false" "since" "since" "false" "0" "since" "/sync" "since" "timeline"
 "timeline" "since" "full_state" "sender" "type" "state_key" "content"
 "invite_state" "state" "state" "invite_state" "content" "state_key" "type"
 "sender" "content" "@" "limit" "from" "GET /_matrix/client/r0/events"
 "timeout" "/sync" "since" "chunk" "from=" "chunk" "/events" "/sync" "from"
 "GET /_matrix/client/r0/initialSync" "/sync" "since" "false" "true" "false"
 "chunk" "/events" "membership" "invite" "/publicRooms" "/sync" "content"
 "user_id" "membership" "join" "state_key" "content" "state_key" "type" "chunk"
 "chunk" "limit" "/sync" "/sync" "content" "@"
 "GET /_matrix/client/r0/events/{eventId}" "event_id"
 "/rooms/{roomId}/event/{eventId}" "/rooms/{roomId}/context/{eventId}" "GET"
 "GET /_matrix/client/r0/rooms/{roomId}/event/{eventId}" "roomId/eventId"
 "GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}"
 "GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}"
 "GET /_matrix/client/r0/rooms/{roomId}/state" "/sync" "content" "@"
 "GET /_matrix/client/r0/rooms/{roomId}/members" "/sync" "content" "user_id"
 "membership" "join" "state_key" "content" "state_key" "type"
 "GET /_matrix/client/r0/rooms/{roomId}/joined_members" "/members"
 "GET /_matrix/client/r0/rooms/{roomId}/messages" "prev_batch" "start" "end"
 "prev_batch" "start" "end" "dir=b" "from" "dir=b" "/sync"
 "GET /_matrix/client/r0/rooms/{roomId}/initialSync" "/sync" "/publicRooms"
 "chunk" "chunk" "limit" "/sync" "/sync" "content" "@"
 "PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}"
 "<room id>" "<event type>" "<state key>" "PUT" "state_key" "POST" "m."
 "PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}" "PUT" "state_key"
 "POST" "m." "state key" "state_key" "state_key" "state_key"
 "PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}"
 "redacted_because" "event_id" "type" "room_id" "sender" "state_key"
 "prev_content" "content" "hashes" "signatures" "depth" "prev_events"
 "prev_state" "auth_events" "origin" "origin_server_ts" "membership"
 "m.room.member" "membership" "m.room.create" "creator" "m.room.join_rules"
 "join_rule" "m.room.power_levels" "ban" "events" "events_default" "kick"
 "redact" "state_default" "users" "users_default" "m.room.aliases" "aliases"
 "m.room.history_visibility" "history_visibility" "unsigned" "redacted_because"
 "m.room.redaction" "redacts"
 "PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}"
 "m.room.create" "creator" "m.room.power_levels" "m.room.join_rules"
 "POST /_matrix/client/r0/createRoom" "m.room.power_levels"
 "power_level_content_override" "preset" "m.room.join_rules"
 "m.room.history_visibility" "m.room.guest_access" "initial_state" "name"
 "topic" "m.room.name" "m.room.topic" "invite" "invite_3pid" "m.room.member"
 "membership: invite" "m.room.third_party_invite" "join_rules"
 "history_visibility" "guest_access" "private_chat" "invite" "shared"
 "can_join" "trusted_private_chat" "invite" "shared" "can_join" "public_chat"
 "public" "shared" "forbidden" "m.room.create" "creation_content" "public"
 "private" "private" "join_rules" "public" "#foo:example.com" "m.room.name"
 "m.room.name" "m.room.topic" "m.room.topic" "M_UNSUPPORTED_ROOM_VERSION"
 "m.federate" "creator" "room_version" "preset" "name" "topic" "visibility"
 "public" "public_chat" "private" "private_chat" "is_direct" "m.room.member"
 "invite" "invite_3pid" "email" "errcode" "errcode" "M_BAD_JSON" "M_NOT_JSON"
 "errcode" "M_ROOM_IN_USE" "power_level" "errcode" "M_INVALID_ROOM_STATE"
 "#friendlyname:server.name" "GET" "m.room.aliases" "#alias:example.com"
 "room_id" "PUT /_matrix/client/r0/directory/room/{roomAlias}"
 "GET /_matrix/client/r0/directory/room/{roomAlias}"
 "DELETE /_matrix/client/r0/directory/room/{roomAlias}" "m.room.power_levels"
 "m.room.power_levels" "m.room.member" "content.membership" "leave"
 "m.room.join_rules" "public" "invite" "GET /_matrix/client/r0/joined_rooms"
 "joined" "POST /_matrix/client/r0/rooms/{roomId}/invite" "m.room.member"
 "errcode" "POST /_matrix/client/r0/rooms/{roomId}/join"
 "/join/{roomIdOrAlias}" "/initialSync" "/sync" "third_party_signed"
 "m.room.third_party_invite" "m.third_party_invite" "room_id" "errcode"
 "POST /_matrix/client/r0/join/{roomIdOrAlias}" "/room/{roomId}/join"
 "/initialSync" "/sync" "third_party_signed" "m.room.third_party_invite"
 "m.third_party_invite" "room_id" "errcode" "/sync" "include_leave" "true"
 "/sync" "POST /_matrix/client/r0/rooms/{roomId}/leave"
 "POST /_matrix/client/r0/rooms/{roomId}/forget"
 "POST /_matrix/client/r0/rooms/{roomId}/kick" "leave" "reason"
 "/rooms/<room id>/state/m.room.member/<user id>" "reason" "errcode"
 "/rooms/<room_id>/ban" "ban" "/rooms/<room id>/state/m.room.member/<user id>"
 "/rooms/<room_id>/unban" "POST /_matrix/client/r0/rooms/{roomId}/ban" "reason"
 "errcode" "POST /_matrix/client/r0/rooms/{roomId}/unban" "errcode"
 "GET /_matrix/client/r0/directory/list/room/{roomId}"
 "PUT /_matrix/client/r0/directory/list/room/{roomId}"
 "GET /_matrix/client/r0/publicRooms" "POST /_matrix/client/r0/publicRooms"
 "include_all_networks" "POST /_matrix/client/r0/user_directory/search"
 "Accept-Language" "PUT /_matrix/client/r0/profile/{userId}/displayname"
 "access_token" "GET /_matrix/client/r0/profile/{userId}/displayname"
 "PUT /_matrix/client/r0/profile/{userId}/avatar_url" "access_token"
 "GET /_matrix/client/r0/profile/{userId}/avatar_url"
 "GET /_matrix/client/r0/profile/{userId}" "displayname" "avatar_url"
 "m.room.member" "join" "displayname" "avatar_url" "m.presence" "displayname"
 "avatar_url" "presence" "retry_after_ms" "/sync" "sender" "room_id"
 "state_key" "type" "event_id" "m." "m.room.aliases" "state_key" "state_key"
 "m.room.aliases" "m.room.canonical_alias" "state_key" "m.room.canonical_alias"
 "alias" "m.room.canonical_alias" "m.room.create" "state_key" "user_id" "true"
 "\"1\"" "m.room.join_rules" "state_key" "public" "invite" "knock" "private"
 "m.room.member" "state_key" "user_id" "membership" "join" "state_key"
 "/rooms/<room id>/invite" "invite" "join" "leave" "ban" "ban" "knock"
 "third_party_invite" "invite" "m.room.third_party_invite" "invite_room_state"
 "unsigned" "StrippedState" "membership" "invite" "m.room.avatar"
 "m.room.canonical_alias" "m.room.join_rules" "m.room.name" "content"
 "state_key" "type" "m.room.power_levels" "state_key" "user_id" "users"
 "user_id" "users_default" "users_default" "m.room.power_levels" "events"
 "state_default" "events_default" "events" "events_default" "state_default"
 "state_default" "m.room.power_levels" "state_default" "events_default"
 "m.room.power_levels" "events_default" "m.room.power_levels" "state_default"
 "events_default" "invite" "kick" "ban" "redact" "m.room.power_levels"
 "m.room.power_levels" "m.room.power_levels" "state_default"
 "m.room.power_levels" "m.room.power_levels" "/createRoom" "events" "events"
 "m.room.power_levels" "user_id" "user_id" "users" "key" "@room"
 "m.room.redaction" "redacts" "Web" "Mobile" "Desktop" "CLI" "Embedded"
 "m.room.message" "msgtype" "body" "msgtype" "msgtypes" "m.image" "m.text"
 "m.room.message.feedback" "delivered" "read" "target_event_id"
 "m.room.message" "m.room.name" "state_key" "m.room.name" "name" "m.room.name"
 "/createRoom" "name" "m.room.topic" "state_key" "/createRoom" "topic"
 "m.room.avatar" "state_key" "url" "image/jpeg" "thumbnail_url" "image/jpeg"
 "m.room.pinned_events" "state_key" "msgtype" "msgtype" "body" "m.text"
 "m.emote" "m.notice" "format" "org.matrix.custom.html" "formatted_body" "body"
 "font" "del" "h1" "h2" "h3" "h4" "h5" "h6" "blockquote" "p" "a" "ul" "ol"
 "sup" "sub" "li" "b" "i" "u" "strong" "em" "strike" "code" "hr" "br" "div"
 "table" "thead" "tbody" "tr" "th" "td" "caption" "pre" "span" "img" "onclick"
 "data-mx-bg-color" "data-mx-color" "font" "data-mx-bg-color" "data-mx-color"
 "span" "data-mx-bg-color" "data-mx-color" "a" "name" "target" "href" "https"
 "http" "ftp" "mailto" "magnet" "img" "width" "height" "alt" "title" "src" "ol"
 "start" "code" "class" "language-" "a" "rel=\"noopener\"" "mx-reply"
 "formatted_body" "mx-reply" "div" "m.text" "formatted_body"
 "org.matrix.custom.html" "body" "format" "m.emote" "m.text" "body" "/me"
 "m.text" "formatted_body" "org.matrix.custom.html" "body" "format" "m.notice"
 "m.notice" "m.notice" "m.text" "m.notice" "m.notice" "m.image" "url"
 "image/jpeg" "thumbnail_url" "image/jpeg" "m.file" "url" "application/msword"
 "thumbnail_url" "image/jpeg" "m.video" "url" "video/mp4" "thumbnail_url"
 "image/jpeg" "m.audio" "url" "audio/aac" "m.location" "thumbnail_url"
 "image/jpeg" "m.room.message" "m.image" "m.file" "mxc://" "url"
 "info.thumbnail_url" "mxc://" "unsigned" "transaction_id" "m.room.member"
 "m.room.member" "displayname" "null" "m.room.member" "displayname"
 "membership: join" "membership: invite" "displayname" "m.room.member"
 "displayname" "@user1:matrix.org" "displayname: Alice" "@user2:example.com"
 "displayname: Alice" "displayname" "m.room.member" "m.room.member" "name"
 "alias" "membership: join" "membership: invite" "state_key" "state_key"
 "membership: join" "membership: invite" "@superuser:example.com"
 "@carol:example.com" "@dan:matrix.org" "m.room.name" "m.room.canonical_alias"
 "m.room.member" "membership: leave" "m.relates_to" "content"
 "m.room.encrypted" "m.relates_to" "content" "m.relates_to" "m.in_reply_to"
 "event_id" "m.room.message" "msgtype" "m.text" "m.notice" "m.emote" "m.file"
 "m.room.message" "m.in_reply_to" "format" "org.matrix.custom.html"
 "formatted_body" "body" "msgtype" "msgtype" "body" "formatted_body"
 "formatted_body" "body" "href" "m.in_reply_to" "formatted_body" "body"
 "m.room.message" "body" "formatted_body" "mx-reply" "m.text" "m.notice" "body"
 "formatted_body" "m.emote" "m.text" "formatted_body" "m.image" "m.video"
 "m.audio" "m.file" "body" "format" "formatted_body" "content" "format"
 "formatted_body" "body" "\"sent a file.\"" "m.image" "\"sent an image.\""
 "m.video" "\"sent a video.\"" "m.audio" "\"sent an audio file\""
 "m.room.message" "msgtype" "body" "m.call.invite" "m.call.candidates"
 "m.call.answer" "m.call.hangup" "m.call.invite" "m.call.invite"
 "m.call.invite" "m.call.invite" "GET /_matrix/client/r0/voip/turnServer"
 "room_id" "room_id" "m.typing" "m.typing" "boolean" "true" "boolean" "false"
 "PUT /_matrix/client/r0/rooms/{roomId}/typing/{userId}" "timeout" "typing"
 "false" "false" "timeout" "m.read" "user_id" "receipt_type" "event_id"
 "m.receipt" "m.read" "/sync" "ephemeral" "user_id" "receipt_type"
 "POST /_matrix/client/r0/rooms/{roomId}/receipt/{receiptType}/{eventId}"
 "m.receipt" "<receipt_type>" "m.read" "m.receipt" "m.fully_read"
 "m.fully_read" "m.fully_read" "m.read" "m.read"
 "/receipts/m.read/$event:domain.com"
 "POST /_matrix/client/r0/rooms/{roomId}/read_markers"
 "/receipt/m.read/$elsewhere:domain.com" "m.fully_read" "m.read"
 "/read_markers" "/receipts/m.read/$event:domain.com" "m.fully_read"
 "/read_markers" "/sync" "online" "idle" "last_active" "m.presence" "presence"
 "online" "unavailable" "offline" "m.presence"
 "PUT /_matrix/client/r0/presence/{userId}/status" "last_active_ago"
 "GET /_matrix/client/r0/presence/{userId}/status"
 "POST /_matrix/client/r0/presence/list/{userId}"
 "GET /_matrix/client/r0/presence/list/{userId}" "online" "last_active_ago"
 "currently_active" "online" "currently_active" "online" "currently_active"
 "unavailable" "unavailable" "online" "Content-Security-Policy"
 "default-src 'none'; script-src 'none';
plugin-types application/pdf; style-src 'unsafe-inline'; object-src 'self';"
 "POST /_matrix/media/r0/upload"
 "GET /_matrix/media/r0/download/{serverName}/{mediaId}" "mxc://" "mxc://"
 "GET /_matrix/media/r0/download/{serverName}/{mediaId}/{fileName}" "mxc://"
 "mxc://" "GET /_matrix/media/r0/thumbnail/{serverName}/{mediaId}" "mxc://"
 "mxc://" "GET /_matrix/media/r0/preview_url" "GET /_matrix/media/r0/config"
 "mxc://127.0.0.1/../../../some_service/etc/passwd" "A-Za-z0-9" "_" "-"
 "server-name" "media-id" "." "/" "/rooms/<room_id>/send" "/sendToDevice" "*"
 "/sync" "type" "/sync" "/sync" "next_batch" "/sync"
 "PUT /_matrix/client/r0/sendToDevice/{eventType}/{txnId}" "/sync" "ToDevice"
 "Event" "GET /_matrix/client/r0/devices"
 "GET /_matrix/client/r0/devices/{deviceId}"
 "PUT /_matrix/client/r0/devices/{deviceId}"
 "DELETE /_matrix/client/r0/devices/{deviceId}"
 "POST /_matrix/client/r0/delete_devices" "ed25519" "curve25519"
 "signed_curve25519" "key" "signatures" "/keys/upload" "/keys/upload"
 "/keys/query" "device_keys" "/keys/query" "/keys/query" "device_keys" "/sync"
 "changed" "device_lists" "/keys/query" "next_batch" "/sync" "/keys/changes"
 "next_batch" "from" "/keys/query" "/keys/query" "device_lists" "/sync"
 "/keys/query" "/keys/query" "changed" "device_lists" "left" "device_lists"
 "mxc://" "m.room.message" "m.file" "m.message" "file" "thumbnail_file"
 "EncryptedFile" "m.message" "url" "thumbnail_url" "EncryptedFile" "sha256"
 "v2" "JWK" "oct" "encrypt" "decrypt" "A256CTR" "true" "/keys/claim"
 "/keys/query" "action" "request" "action" "cancel_request" "cancel_request"
 "request" "request_id" "requesting_device_id" "m." "m.olm.v1"
 "m.olm.v1.ecdh-curve25519-hdkfsha256.hmacsha256.hkdfsha256-aes256-cbc-hmac64sha256"
 "m.olm.v1.curve25519-aes-sha2" "m.olm.v1.curve25519-aes-sha2" "ciphertext"
 "body" "type" "sender" "recipient" "recipient_keys" "sender_key" "ed25519"
 "keys" "/keys/query" "m.megolm.v1.aes-sha2" "m.megolm.v1.aes-sha2"
 "sender_key" "keys.ed25519" "m.room.encryption" "m.megolm.v1.aes-sha2"
 "algorithm" "m.room_key" "m.room_key" "m.room.encryption" "state_key"
 "604800000" "100" "m.room.encrypted" "m.room_key" "m.room.encrypted"
 "m.room_key_request" "action" "request" "m.forwarded_room_key"
 "m.room.encrypted" "POST /_matrix/client/r0/keys/upload"
 "<algorithm>:<key_id>" "<algorithm>:<device_id>" "<algorithm>:<device_id>"
 "POST /_matrix/client/r0/keys/query" "device_keys" "/keys/upload" "unsigned"
 "<algorithm>:<device_id>" "<algorithm>:<device_id>"
 "POST /_matrix/client/r0/keys/claim" "one_time_keys" "<algorithm>:<key_id>"
 "GET /_matrix/client/r0/keys/changes" "join" "from" "to" "next_batch" "/sync"
 "next_batch" "/sync" "device_lists" "/sync" "/sync" "since" "/keys/query"
 "/keys/changes" "one_time_keys_count" "one_time_key_counts" "/keys/upload"
 "DeviceLists" "changed" "changed" "world_readable" "m.room.history_visibility"
 "m.room.history_visibility" "world_readable" "m.room.history_visibility"
 "shared" "invited" "invite" "join" "joined" "join" "m.room.history_visibility"
 "m.room.history_visibility" "state_key" "world_readable" "history_visibility"
 "shared" "history_visibility" "world_readable" "membership" "join"
 "history_visibility" "shared" "membership" "invite" "history_visibility"
 "invited" "m.room.history_visibility" "history_visibility"
 "m.room.history_visibility" "history_visibility" "world_readable" "joined"
 "joined" "world_readable" "m.room.member" "membership" "m.room.member" "join"
 "join" "history_visibility" "joined" "history_visibility" "shared"
 "GET /_matrix/client/r0/pushers" "/set" "\"http\"" "kind" "http"
 "POST /_matrix/client/r0/pushers/set" "kind" "\"email\"" "\"http\""
 "\"email\"" "null" "kind" "\"email\"" "\"m.email\"" "kind" "http" "url"
 "false" "kind" "http" "/_matrix/push/v1/notify" "kind" "http"
 "GET /_matrix/client/r0/notifications" "highlight" "from" "/notifications"
 "content" "timeline" "kind" "rule_id" "rule_id" "rule_ids" "kind" "override"
 "content" "pattern" "pattern" "event_match" "room" "rule_id" "sender"
 "rule_id" "underride" "override" "content" "room" "sender" "kind" "actions"
 "actions" "notify" "dont_notify" "coalesce" "notify" "set_tweak" "tweaks"
 "set_tweak" "value" "{ \"set_tweak\": \"sound\", \"value\": \"default\" }"
 "set_tweak" "sound" "default" "highlight" "highlight" "true" "highlight"
 "rule_id" ".m.rule.master" ".m.rule.suppress_notices" "msgtype" "notice"
 "override" "content" "sender" "room" ".m.rule.invite_for_me"
 ".m.rule.member_event" "m.room.member_event" ".m.rule.contains_display_name"
 ".m.rule.roomnotif" "@room" ".m.rule.contains_user_name" "content"
 ".m.rule.call" ".m.rule.encrypted_room_one_to_one" ".m.rule.room_one_to_one"
 ".m.rule.message" ".m.rule.encrypted" "action" "rule_id" "event_match" "key"
 "content.body" "pattern" "contains_display_name" "content.body"
 "room_member_count" "is" "==" "<" ">" ">=" "<=" "<" "=="
 "sender_notification_permission" "key" "room" "key" "notifications"
 "GET /_matrix/client/r0/pushrules/" "scope" "/pushrules/global/" "global"
 "underride" "override" "content" "event_match" "event_match"
 "room_member_count" "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}"
 "global" "underride" "override" "content" "event_match" "event_match"
 "room_member_count" "actions" "conditions"
 "DELETE /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}" "global"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}" "underride"
 "override" "content" "global" "rule_id" "event_match" "event_match"
 "room_member_count"
 "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled" "global"
 "device/<profile_tag>" "profile_tag"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/enabled" "global"
 "GET /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions" "global"
 "device/<profile_tag>" "profile_tag"
 "PUT /_matrix/client/r0/pushrules/{scope}/{kind}/{ruleId}/actions" "global"
 "m.push_rules" "account_data" "/sync" "!dj234r78wl45Gh4D:matrix.org"
 "@spambot:matrix.org" "SSByZWFsbHkgbGlrZSBjYWtl" "/invite" "m.room.member"
 "content.membership" "invite" "content.third_party_invite"
 "m.room.third_party_invite" "state_key" "m.room.member"
 "POST /_matrix/client/r0/rooms/{roomId}/invite" "m.room.member"
 "m.room.third_party_invite" "m.room.third_party_invite" "email" "errcode"
 "/invite" "m.room.third_party_invite" "content.third_party_invite.signed"
 "m.room.third_party_invite" "m.room.member" "membership: invite"
 "m.room.third_party_invite" "key_validity_url" "key_validity_url"
 "m.room.member" "/exchange_third_party_invite/:roomId" "m.room.member"
 "/3pid/onbind" "signed" "key_validity_url" "key_validity_url"
 "POST /_matrix/client/r0/search" "next_batch" "\"rank\"" "'senders'" "'types'"
 "'*'" "'rooms'" "true" "url" "false" "false" "5" "5" "false" "include_state"
 "true" "string" "State Event" "string" "room_id" "sender" "string" "string"
 "/sync" "/sync" "content" "@" "room_events" "room_events" "content.body"
 "m.room.message" "content.name" "m.room.name" "content.topic" "m.room.topic"
 "rank" "rank" "count" "rank" "recent" "rank" "room_id" "room_id" "event_ids"
 "room_id" "sender" "next_batch" "next_batch" "next_batch" "next_batch"
 "search_categories.<category>.next_batch"
 "search_categories.<category>.groups.<group_key>.<group_id>.next_batch"
 "next_batch" "kind" "guest" "register" "guest_access_token" "username"
 "m.room.guest_access" "state_key" "m.room.guest_access" "guest_access"
 "can_join" "m.room.guest_access" "m.room.member" "leave" "world_readable"
 "/events" "GET /_matrix/client/r0/events" "timeout" "/events" "/events"
 "chunk" "from=" "chunk" "/events" "/sync" "from" "m.room.history_visibility"
 "history_visibility" "world_readable" "world_readable" "m.tag" "account_data"
 "m.tag" "tags" "order" "order" "0.2" "order" "0.7" "order" "order" "m.*" "u.*"
 "u." "tld.name.*" "tld.name.*" "u.*" "u." "m.*" "m.favourite" "m.lowpriority"
 "m.tag" "[0,1]" "GET /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags"
 "[0,1]" "PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}"
 "[0,1]" "DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}"
 "account_data" "/sync" "/events" "account_data" "/sync" "m.tag" "/events"
 "room_id" "PUT /_matrix/client/r0/user/{userId}/account_data/{type}"
 "account_data"
 "PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/account_data/{type}"
 "account_data" "GET /_matrix/client/r0/admin/whois/{userId}"
 "GET /_matrix/client/r0/rooms/{roomId}/context/{eventId}" "/sync" "/sync"
 "content" "@" "/login/cas/redirect" "/login/cas/ticket" "/login"
 "/login/cas/redirect" "redirectUrl" "redirectUrl"
 "GET /_matrix/client/r0/login/cas/redirect" "service" "/login/cas/ticket"
 "redirectUrl" "redirectUrl=https://client.example.com/?q=p"
 "https://cas.example.com/?service=https%3A%2F%2Fserver.example.com%2F_matrix%2Fclient%2Fr0%2Flogin%2Fcas%2Fticket%3FredirectUrl%3Dhttps%253A%252F%252Fclient.example.com%252F%253Fq%253Dp"
 "GET /_matrix/client/r0/login/cas/ticket" "/login/cas/redirect" "service"
 "/proxyValidate" "redirectUrl" "loginToken" "401
Unauthorized"
 "redirectUrl" "/login/cas/redirect" "/login/cas/redirect" "service"
 "/login/cas/ticket" "redirectUrl" "/login/cas/ticket" "user_id"
 "m.login.token" "/login" "m.direct" "account_data" "m.direct" "is_direct"
 "/createRoom" "is_direct" "is_direct" "m.direct"
 "/user/<user_id>/account_data/<type>" "is_direct" "/createRoom" "is_direct"
 "/createRoom" "m.ignored_user_list" "account_data" "m.ignored_user_list"
 "m.ignored_user_list" "/user/<user_id>/account_data/<type>" "/sync"
 "m.ignored_user_list" "m.sticker" "timeline" "/sync" "m.sticker" "url"
 "mxc://" "image/jpeg" "thumbnail_url" "image/jpeg" "info" "m.sticker" "info"
 "POST /_matrix/client/r0/rooms/{roomId}/report/{eventId}"
 "GET /_matrix/client/r0/thirdparty/protocols" "user_fields" "location_fields"
 "string" "fields" "GET /_matrix/client/r0/thirdparty/protocol/{protocol}"
 "user_fields" "location_fields" "string" "fields"
 "GET /_matrix/client/r0/thirdparty/location/{protocol}"
 "GET /_matrix/client/r0/thirdparty/user/{protocol}"
 "GET /_matrix/client/r0/thirdparty/location"
 "GET /_matrix/client/r0/thirdparty/user"
 "POST /_matrix/client/r0/user/{userId}/openid/request_token" "/sync"
 "GET /openid/userinfo" "Bearer" "id_token" "m.federate" "m.room.server_acl"
 "state_key" "allow" "deny" "?" "*" "evil.com" "evil.com:8448" "evil.com:1234"
 "evil.com" "m.room.server_acl" "allow_ip_literals" "false" "deny" "allow"
 "allow" "[ \"*\" ]" "deny" "prev_events" "false" "*" "?" "*" "?"
 "allow_ip_literals" "msgtype" "m.text" "m.emote" "m.notice" "format"
 "org.matrix.custom.html" "formatted_body" "formatted_body" "matrix.to URI"
 "body")